apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend-nginxapp
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-nginxapp
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 31234
