apiVersion: apps/v1
kind: RepilcaSet
metadata:
  name: myapp2-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata: # Dictionary
      name: myapp2-pod
      labels: 
        app: myapp2
    spec:
      containers: 
        - name: myapp2-container
          image: stacksimplify/kubenginx:1.0.0
          ports: 
            - containerPort: 80
          
